Adjusting sample types to match MIABIS
samply/searchbroker pull request #44
Opened 2022-02-14 16:05 UTC by DavidCroftDKFZ

The liquid and tissue sample types being used in the Sample Locator
MDR largely overlap with the MIABIS sample types, see:

https://samply.github.io/bbmri-fhir-ig/ValueSet-SampleMaterialType.html

However, there are some differences. The following sample types
are only to be found in MIABIS, not in the Sample Locator MDR:

buffy-coat
dried-whole-blood
blood-plasma
plasma-heparin
plasma-cell-free
plasma-other
swab
tumor-tissue-ffpe
normal-tissue-ffpe
other-tissue-ffpe
g-dna
derivative-other

Additionally, the following sample types are only found in the Sample
Locator MDR, not in MIABIS:

Whole blood-EDTA
Whole blood stabilised
Urine spontaneous
Urine cumulative
Tissue stored in PAXgene or similarly
Plasma stabilised

In order to provide the new sample types, an updated version of the MDR
will be made available.

This mapping file has been modified with two aims in mind:

1. To expand the range of sample types to encompass all of the types
   known to MIABIS.
2. To map legacy sample types onto accepted MIABIS sample types,
   allowing this code to continue working with older versions of the
   MDR.

**What's in the PR**
* ...

**How to test manually**
* ...

2022-02-17 07:19 UTC, TasDeniz commented
Please edit the changelog file and increase the pom version

2022-02-17 09:56 UTC, TasDeniz commented on pom.xml
> +    <version>8.5.0-SNAPSHOT</version>
if this version doesn't work with the current master branch of the sample.locator without chaning something then the version must be 9.0.0

2022-02-18 07:16 UTC, TasDeniz approved these changes

2022-02-18 08:17 UTC, alexanderkiel requested changes
It would be good, if you build up from my branch `new-sample-type`. Also, we liked to use a new MDR URN for the new sample types, so that the searchbroker says compatible with the current Sample Locator. That new URN has to exist in the MDR.

2022-04-27 14:31 UTC, merged